version: "3.2"
services:
  qrcode:
    build: .
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'images'
      OR CODE DEFAULT URL: 'https://hub.docker.com/r/siddharthreddy47/qrcode'
      QR_CODE_DEFAULT_FILE_NAME: 'home_page.png'
    volumes:
      - .:/home /myuser